### PR TITLE
feat: Use expiration overlay, claim badge and fix badge lists #65 #66 #85 #86 #87 #88

### LINKED ISSUE #65: My profile: claim badges
Users should be able to claim the badges that are ready to claim on their profile

### PR DESCRIPTION
**Pull request by ramabit**
# Description
Fixes #65  #66 #85 #86 #87 #88 
- Adding usage of expiration overlay
- Add claim badge button if review is completed (pending ready 100%)
- Fix loading badge lists
- Improve all profiles, also for curator and creator

### CODE REVIEW

File: src/constants/helpers.ts [hunk 1]
```diff
@@ -5,4 +5,10 @@ export function nowInSeconds() {
   return Math.floor(Date.now() / 1000)
 }
 
+export function nowPlusOneMonthInSeconds() {
+  const date = new Date()
+  date.setMonth(date.getMonth() + 3)
```
Comment (FedeMadoery) [inline src/constants/helpers.ts:10]: How does this work if its December and we add 3? I always use Dayjs for this, I don't even remember how the native one works ehehehe

File: src/pagePartials/profile/myProfile/NearToExpireList.tsx [hunk 2]
```diff
@@ -2,49 +2,109 @@ import { useRouter } from 'next/navigation'
...
+  const { t } = useTranslation()
   const router = useRouter()
   const gql = useSubgraph()
+  const md = useSizeMD()
+  const lg = useSizeLG()
+  const { getTimeLeftToExpire, timestampToDate } = useDate()
+  const { address: ownerAddress } = useWeb3Connection()
 
-  const badgesInReview = gql.useBadgesInReview({ date: now })
+  // TODO now "NEAR TO EXPIRE" is in max 1 month, we will change this to configurable time
```
Comment (FedeMadoery) [inline src/pagePartials/profile/myProfile/NearToExpireList.tsx:31]: Add a config button, on the right side of the header, maybe a wear or something similar, where the user can choose btw "One month", "Two weeks" "One week"

I do this comment, so we can create a task from it :)

File: src/pagePartials/profile/myProfile/PendingList.tsx [hunk 3]
```diff
@@ -1,61 +1,119 @@
...
       const pendingTimeDurationSeconds: number =
-        badgeInReview.badgeModel.badgeModelKleros?.challengePeriodDuration
+        badge.badgeModel.badgeModelKleros?.challengePeriodDuration
       const timeLeft: TimeLeft = getTimeLeft(dueDate)
       const progressPercentage = getPendingTimeProgressPercentage(
         dueDate,
         pendingTimeDurationSeconds,
       )
 
+      async function handleClaimBadge(badgeId: string) {
```
Comment (FedeMadoery) [inline src/pagePartials/profile/myProfile/PendingList.tsx:47]: Would be nice if we show a modal/popup that shows to the user how much money will be given back to him from the mint deposit.

I do this comment, so we can create a task from it :)

**Review by FedeMadoery — APPROVED** [review]

File: src/pagePartials/profile/Profile.tsx [hunk 4]
```diff
@@ -49,7 +51,7 @@ const Profile = () => {
         <InfoPreview address={user?.id || ''} />
       </SafeSuspense>
       {!filterType && <MyProfileSection />}
-      {filterType === 'badgesInReview' && <BadgesInReviewSection />}
+      {filterType === 'badgesIAmReviewing' && <BadgesIAmReviewingSection />}
```
Comment (Agupane) [inline src/pagePartials/profile/Profile.tsx:54]: Would be possible to create an enum with the `filterTypes`? I guess it would scale better than hardcode this everytime

File: src/subgraph/queries/badge.ts [hunk 5]
```diff
@@ -43,6 +43,53 @@ export const MY_BADGES = gql`
...
+        account_starts_with: $badgeReceiver
+        account_not: $userAddress
+      }
+    ) {
+      ...BadgeWithJustIds
+    }
+  }
+`
+
+// export const BADGES_USER_IS_REVIEWING = gql`
```
Comment (Agupane) [inline src/subgraph/queries/badge.ts:80]: is this on TODO or can be removed?

**Review by Agupane — CHANGES_REQUESTED** [review]

File: src/pagePartials/profile/myProfile/NearToExpireList.tsx (hunk 2 above)
Comment (ramabit) [reply src/pagePartials/profile/myProfile/NearToExpireList.tsx:31]: added #140

File: src/pagePartials/profile/myProfile/PendingList.tsx (hunk 3 above)
Comment (ramabit) [reply src/pagePartials/profile/myProfile/PendingList.tsx:47]: added #141

**Review by FedeMadoery — APPROVED** [review]
